package com.megalogaminguk.megalosaio.datagen;

import com.megalogaminguk.megalosaio.Constants;
import com.megalogaminguk.megalosaio.init.ModBlocks;
import com.megalogaminguk.megalosaio.init.ModCreativeTabs;
import com.megalogaminguk.megalosaio.init.ModItems;
import net.minecraft.data.PackOutput;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.contents.TranslatableContents;
import net.neoforged.neoforge.common.data.LanguageProvider;

public class MegalosAIOEnglishLanguageProvider extends LanguageProvider {
    public MegalosAIOEnglishLanguageProvider(PackOutput output) {
        super(output, Constants.MOD_ID, "en_us");
    }

    @Override
    protected void addTranslations() {
        //***Items***
        //Items - Ingot
        add(ModItems.ALUMINIUM_INGOT.get(), "Aluminium Ingot");
        add(ModItems.ANTIMONY_INGOT.get(), "Antimony Ingot");
        add(ModItems.ARSENIC_INGOT.get(), "Arsenic Ingot");
        add(ModItems.BARIUM_INGOT.get(), "Barium Ingot");
        add(ModItems.BERYLLIUM_INGOT.get(), "Beryllium Ingot");
        add(ModItems.BISMUTH_INGOT.get(), "Bismuth Ingot");
        add(ModItems.CADMIUM_INGOT.get(), "Cadmium Ingot");
        add(ModItems.CALCIUM_INGOT.get(), "Calcium Ingot");
        add(ModItems.CAESIUM_INGOT.get(), "Caesium Ingot");
        add(ModItems.CHROMIUM_INGOT.get(), "Chromium Ingot");
        add(ModItems.CINNABAR_INGOT.get(), "Mercury Ingot");
        add(ModItems.COBALT_INGOT.get(), "Cobalt Ingot");
        add(ModItems.GERMANIUM_INGOT.get(), "Germanium Ingot");
        add(ModItems.GALLIUM_INGOT.get(), "Gallium Ingot");
        add(ModItems.HAFNIUM_INGOT.get(), "Hafnium Ingot");
        add(ModItems.INDIUM_INGOT.get(), "Indium Ingot");
        add(ModItems.IRIDIUM_INGOT.get(), "Iridium Ingot");
        add(ModItems.LEAD_INGOT.get(), "Lead Ingot");
        add(ModItems.LITHIUM_INGOT.get(), "Lithium Ingot");
        add(ModItems.MAGNESIUM_INGOT.get(), "Magnesium Ingot");
        add(ModItems.MANGANESE_INGOT.get(), "Manganese Ingot");
        add(ModItems.MOLYBDENUM_INGOT.get(), "Molybdenum Ingot");
        add(ModItems.NICKEL_INGOT.get(), "Nickel Ingot");
        add(ModItems.NIOBIUM_INGOT.get(), "Niobium Ingot");
        add(ModItems.OSMIUM_INGOT.get(), "Osmium Ingot");
        add(ModItems.PALLADIUM_INGOT.get(), "Palladium Ingot");
        add(ModItems.PHOSPHORUS_INGOT.get(), "Phosphorus Ingot");
        add(ModItems.PLATINUM_INGOT.get(), "Platinum Ingot");
        add(ModItems.POTASSIUM_INGOT.get(), "Potassium Ingot");
        add(ModItems.RHENIUM_INGOT.get(), "Rhenium Ingot");
        add(ModItems.RHODIUM_INGOT.get(), "Rhodium Ingot");
        add(ModItems.RUBIDIUM_INGOT.get(), "Rubidium Ingot");
        add(ModItems.RUTHENIUM_INGOT.get(), "Ruthenium Ingot");
        add(ModItems.SCANDIUM_INGOT.get(), "Scandium Ingot");
        add(ModItems.SELENIUM_INGOT.get(), "Selenium Ingot");
        add(ModItems.SILICON_INGOT.get(), "Silicon Ingot");
        add(ModItems.SILVER_INGOT.get(), "Silver Ingot");
        add(ModItems.SODIUM_INGOT.get(), "Sodium Ingot");
        add(ModItems.STRONTIUM_INGOT.get(), "Strontium Ingot");
        add(ModItems.TANTALUM_INGOT.get(), "Tantalum Ingot");
        add(ModItems.TECHNETIUM_INGOT.get(), "Technetium Ingot");
        add(ModItems.TELLURIUM_INGOT.get(), "Tellurium Ingot");
        add(ModItems.THALLIUM_INGOT.get(), "Thallium Ingot");
        add(ModItems.TIN_INGOT.get(), "Tin Ingot");
        add(ModItems.TITANIUM_INGOT.get(), "Titanium Ingot");
        add(ModItems.TUNGSTEN_INGOT.get(), "Tungsten Ingot");
        add(ModItems.VANADIUM_INGOT.get(), "Vanadium Ingot");
        add(ModItems.YTTRIUM_INGOT.get(), "Yttrium Ingot");
        add(ModItems.ZINC_INGOT.get(), "Zinc Ingot");
        add(ModItems.ZIRCONIUM_INGOT.get(), "Zirconium Ingot");

        //Items - Nugget
        add(ModItems.ALUMINIUM_NUGGET.get(), "Aluminium Nugget");
        add(ModItems.ANTIMONY_NUGGET.get(), "Antimony Nugget");
        add(ModItems.ARSENIC_NUGGET.get(), "Arsenic Nugget");
        add(ModItems.BARIUM_NUGGET.get(), "Barium Nugget");
        add(ModItems.BERYLLIUM_NUGGET.get(), "Beryllium Nugget");
        add(ModItems.BISMUTH_NUGGET.get(), "Bismuth Nugget");
        add(ModItems.CADMIUM_NUGGET.get(), "Cadmium Nugget");
        add(ModItems.CALCIUM_NUGGET.get(), "Calcium Nugget");
        add(ModItems.CAESIUM_NUGGET.get(), "Caesium Nugget");
        add(ModItems.CHROMIUM_NUGGET.get(), "Chromium Nugget");
        add(ModItems.CINNABAR_NUGGET.get(), "Mercury Nugget");
        add(ModItems.COBALT_NUGGET.get(), "Cobalt Nugget");
        add(ModItems.GERMANIUM_NUGGET.get(), "Germanium Nugget");
        add(ModItems.GALLIUM_NUGGET.get(), "Gallium Nugget");
        add(ModItems.HAFNIUM_NUGGET.get(), "Hafnium Nugget");
        add(ModItems.INDIUM_NUGGET.get(), "Indium Nugget");
        add(ModItems.IRIDIUM_NUGGET.get(), "Iridium Nugget");
        add(ModItems.LEAD_NUGGET.get(), "Lead Nugget");
        add(ModItems.LITHIUM_NUGGET.get(), "Lithium Nugget");
        add(ModItems.MAGNESIUM_NUGGET.get(), "Magnesium Nugget");
        add(ModItems.MANGANESE_NUGGET.get(), "Manganese Nugget");
        add(ModItems.MOLYBDENUM_NUGGET.get(), "Molybdenum Nugget");
        add(ModItems.NICKEL_NUGGET.get(), "Nickel Nugget");
        add(ModItems.NIOBIUM_NUGGET.get(), "Niobium Nugget");
        add(ModItems.OSMIUM_NUGGET.get(), "Osmium Nugget");
        add(ModItems.PALLADIUM_NUGGET.get(), "Palladium Nugget");
        add(ModItems.PHOSPHORUS_NUGGET.get(), "Phosphorus Nugget");
        add(ModItems.PLATINUM_NUGGET.get(), "Platinum Nugget");
        add(ModItems.POTASSIUM_NUGGET.get(), "Potassium Nugget");
        add(ModItems.RHENIUM_NUGGET.get(), "Rhenium Nugget");
        add(ModItems.RHODIUM_NUGGET.get(), "Rhodium Nugget");
        add(ModItems.RUBIDIUM_NUGGET.get(), "Rubidium Nugget");
        add(ModItems.RUTHENIUM_NUGGET.get(), "Ruthenium Nugget");
        add(ModItems.SCANDIUM_NUGGET.get(), "Scandium Nugget");
        add(ModItems.SELENIUM_NUGGET.get(), "Selenium Nugget");
        add(ModItems.SILICON_NUGGET.get(), "Silicon Nugget");
        add(ModItems.SILVER_NUGGET.get(), "Silver Nugget");
        add(ModItems.SODIUM_NUGGET.get(), "Sodium Nugget");
        add(ModItems.STRONTIUM_NUGGET.get(), "Strontium Nugget");
        add(ModItems.TANTALUM_NUGGET.get(), "Tantalum Nugget");
        add(ModItems.TECHNETIUM_NUGGET.get(), "Technetium Nugget");
        add(ModItems.TELLURIUM_NUGGET.get(), "Tellurium Nugget");
        add(ModItems.THALLIUM_NUGGET.get(), "Thallium Nugget");
        add(ModItems.TIN_NUGGET.get(), "Tin Nugget");
        add(ModItems.TITANIUM_NUGGET.get(), "Titanium Nugget");
        add(ModItems.TUNGSTEN_NUGGET.get(), "Tungsten Nugget");
        add(ModItems.VANADIUM_NUGGET.get(), "Vanadium Nugget");
        add(ModItems.YTTRIUM_NUGGET.get(), "Yttrium Nugget");
        add(ModItems.ZINC_NUGGET.get(), "Zinc Nugget");
        add(ModItems.ZIRCONIUM_NUGGET.get(), "Zirconium Nugget");

        //Items - Dust
        add(ModItems.ALUMINIUM_DUST.get(), "Aluminium Dust");
        add(ModItems.ANTIMONY_DUST.get(), "Antimony Dust");
        add(ModItems.ARSENIC_DUST.get(), "Arsenic Dust");
        add(ModItems.BARIUM_DUST.get(), "Barium Dust");
        add(ModItems.BERYLLIUM_DUST.get(), "Beryllium Dust");
        add(ModItems.BISMUTH_DUST.get(), "Bismuth Dust");
        add(ModItems.CADMIUM_DUST.get(), "Cadmium Dust");
        add(ModItems.CALCIUM_DUST.get(), "Calcium Dust");
        add(ModItems.CAESIUM_DUST.get(), "Caesium Dust");
        add(ModItems.CHROMIUM_DUST.get(), "Chromium Dust");
        add(ModItems.CINNABAR_DUST.get(), "Mercury Dust");
        add(ModItems.COBALT_DUST.get(), "Cobalt Dust");
        add(ModItems.GERMANIUM_DUST.get(), "Germanium Dust");
        add(ModItems.GALLIUM_DUST.get(), "Gallium Dust");
        add(ModItems.HAFNIUM_DUST.get(), "Hafnium Dust");
        add(ModItems.INDIUM_DUST.get(), "Indium Dust");
        add(ModItems.IRIDIUM_DUST.get(), "Iridium Dust");
        add(ModItems.LEAD_DUST.get(), "Lead Dust");
        add(ModItems.LITHIUM_DUST.get(), "Lithium Dust");
        add(ModItems.MAGNESIUM_DUST.get(), "Magnesium Dust");
        add(ModItems.MANGANESE_DUST.get(), "Manganese Dust");
        add(ModItems.MOLYBDENUM_DUST.get(), "Molybdenum Dust");
        add(ModItems.NICKEL_DUST.get(), "Nickel Dust");
        add(ModItems.NIOBIUM_DUST.get(), "Niobium Dust");
        add(ModItems.OSMIUM_DUST.get(), "Osmium Dust");
        add(ModItems.PALLADIUM_DUST.get(), "Palladium Dust");
        add(ModItems.PHOSPHORUS_DUST.get(), "Phosphorus Dust");
        add(ModItems.PLATINUM_DUST.get(), "Platinum Dust");
        add(ModItems.POTASSIUM_DUST.get(), "Potassium Dust");
        add(ModItems.RHENIUM_DUST.get(), "Rhenium Dust");
        add(ModItems.RHODIUM_DUST.get(), "Rhodium Dust");
        add(ModItems.RUBIDIUM_DUST.get(), "Rubidium Dust");
        add(ModItems.RUTHENIUM_DUST.get(), "Ruthenium Dust");
        add(ModItems.SCANDIUM_DUST.get(), "Scandium Dust");
        add(ModItems.SELENIUM_DUST.get(), "Selenium Dust");
        add(ModItems.SILICON_DUST.get(), "Silicon Dust");
        add(ModItems.SILVER_DUST.get(), "Silver Dust");
        add(ModItems.SODIUM_DUST.get(), "Sodium Dust");
        add(ModItems.STRONTIUM_DUST.get(), "Strontium Dust");
        add(ModItems.TANTALUM_DUST.get(), "Tantalum Dust");
        add(ModItems.TECHNETIUM_DUST.get(), "Technetium Dust");
        add(ModItems.TELLURIUM_DUST.get(), "Tellurium Dust");
        add(ModItems.THALLIUM_DUST.get(), "Thallium Dust");
        add(ModItems.TIN_DUST.get(), "Tin Dust");
        add(ModItems.TITANIUM_DUST.get(), "Titanium Dust");
        add(ModItems.TUNGSTEN_DUST.get(), "Tungsten Dust");
        add(ModItems.VANADIUM_DUST.get(), "Vanadium Dust");
        add(ModItems.YTTRIUM_DUST.get(), "Yttrium Dust");
        add(ModItems.ZINC_DUST.get(), "Zinc Dust");
        add(ModItems.ZIRCONIUM_DUST.get(), "Zirconium Dust");

        //Vanilla - Dust
        add(ModItems.COPPER_DUST.get(), "Copper Dust");
        add(ModItems.IRON_DUST.get(), "Iron Dust");
        add(ModItems.GOLD_DUST.get(), "Gold Dust");
        add(ModItems.COAL_DUST.get(), "Coal Dust");

        //Items - Raw
        add(ModItems.RAW_ALUMINIUM.get(), "Raw Aluminium");
        add(ModItems.RAW_ANTIMONY.get(), "Raw Antimony");
        add(ModItems.RAW_ARSENIC.get(), "Raw Arsenic");
        add(ModItems.RAW_BARIUM.get(), "Raw Barium");
        add(ModItems.RAW_BERYLLIUM.get(), "Raw Beryllium");
        add(ModItems.RAW_BISMUTH.get(), "Raw Bismuth");
        add(ModItems.RAW_CADMIUM.get(), "Raw Cadmium");
        add(ModItems.RAW_CALCIUM.get(), "Raw Calcium");
        add(ModItems.RAW_CAESIUM.get(), "Raw Caesium");
        add(ModItems.RAW_CHROMIUM.get(), "Raw Chromium");
        add(ModItems.RAW_CINNABAR.get(), "Raw Mercury");
        add(ModItems.RAW_COBALT.get(), "Raw Cobalt");
        add(ModItems.RAW_GERMANIUM.get(), "Raw Germanium");
        add(ModItems.RAW_GALLIUM.get(), "Raw Gallium");
        add(ModItems.RAW_HAFNIUM.get(), "Raw Hafnium");
        add(ModItems.RAW_INDIUM.get(), "Raw Indium");
        add(ModItems.RAW_IRIDIUM.get(), "Raw Iridium");
        add(ModItems.RAW_LEAD.get(), "Raw Lead");
        add(ModItems.RAW_LITHIUM.get(), "Raw Lithium");
        add(ModItems.RAW_MAGNESIUM.get(), "Raw Magnesium");
        add(ModItems.RAW_MANGANESE.get(), "Raw Manganese");
        add(ModItems.RAW_MOLYBDENUM.get(), "Raw Molybdenum");
        add(ModItems.RAW_NICKEL.get(), "Raw Nickel");
        add(ModItems.RAW_NIOBIUM.get(), "Raw Niobium");
        add(ModItems.RAW_OSMIUM.get(), "Raw Osmium");
        add(ModItems.RAW_PALLADIUM.get(), "Raw Palladium");
        add(ModItems.RAW_PHOSPHORUS.get(), "Raw Phosphorus");
        add(ModItems.RAW_PLATINUM.get(), "Raw Platinum");
        add(ModItems.RAW_POTASSIUM.get(), "Raw Potassium");
        add(ModItems.RAW_RHENIUM.get(), "Raw Rhenium");
        add(ModItems.RAW_RHODIUM.get(), "Raw Rhodium");
        add(ModItems.RAW_RUBIDIUM.get(), "Raw Rubidium");
        add(ModItems.RAW_RUTHENIUM.get(), "Raw Ruthenium");
        add(ModItems.RAW_SCANDIUM.get(), "Raw Scandium");
        add(ModItems.RAW_SELENIUM.get(), "Raw Selenium");
        add(ModItems.RAW_SILICON.get(), "Raw Silicon");
        add(ModItems.RAW_SILVER.get(), "Raw Silver");
        add(ModItems.RAW_SODIUM.get(), "Raw Sodium");
        add(ModItems.RAW_STRONTIUM.get(), "Raw Strontium");
        add(ModItems.RAW_TANTALUM.get(), "Raw Tantalum");
        add(ModItems.RAW_TECHNETIUM.get(), "Raw Technetium");
        add(ModItems.RAW_TELLURIUM.get(), "Raw Tellurium");
        add(ModItems.RAW_THALLIUM.get(), "Raw Thallium");
        add(ModItems.RAW_TIN.get(), "Raw Tin");
        add(ModItems.RAW_TITANIUM.get(), "Raw Titanium");
        add(ModItems.RAW_TUNGSTEN.get(), "Raw Tungsten");
        add(ModItems.RAW_VANADIUM.get(), "Raw Vanadium");
        add(ModItems.RAW_YTTRIUM.get(), "Raw Yttrium");
        add(ModItems.RAW_ZINC.get(), "Raw Zinc");
        add(ModItems.RAW_ZIRCONIUM.get(), "Raw Zirconium");

        //***Blocks***
        //Blocks - Ore
        add(ModBlocks.ALUMINIUM_ORE.block().get(), "Aluminium Ore");
        add(ModBlocks.ANTIMONY_ORE.block().get(), "Antimony Ore");
        add(ModBlocks.ARSENIC_ORE.block().get(), "Arsenic Ore");
        add(ModBlocks.BARIUM_ORE.block().get(), "Barium Ore");
        add(ModBlocks.BERYLLIUM_ORE.block().get(), "Beryllium Ore");
        add(ModBlocks.BISMUTH_ORE.block().get(), "Bismuth Ore");
        add(ModBlocks.CADMIUM_ORE.block().get(), "Cadmium Ore");
        add(ModBlocks.CALCIUM_ORE.block().get(), "Calcium Ore");
        add(ModBlocks.CAESIUM_ORE.block().get(), "Caesium Ore");
        add(ModBlocks.CHROMIUM_ORE.block().get(), "Chromium Ore");
        add(ModBlocks.CINNABAR_ORE.block().get(), "Mercury Ore");
        add(ModBlocks.COBALT_ORE.block().get(), "Cobalt Ore");
        add(ModBlocks.GERMANIUM_ORE.block().get(), "Germanium Ore");
        add(ModBlocks.GALLIUM_ORE.block().get(), "Gallium Ore");
        add(ModBlocks.HAFNIUM_ORE.block().get(), "Hafnium Ore");
        add(ModBlocks.INDIUM_ORE.block().get(), "Indium Ore");
        add(ModBlocks.IRIDIUM_ORE.block().get(), "Iridium Ore");
        add(ModBlocks.LEAD_ORE.block().get(), "Lead Ore");
        add(ModBlocks.LITHIUM_ORE.block().get(), "Lithium Ore");
        add(ModBlocks.MAGNESIUM_ORE.block().get(), "Magnesium Ore");
        add(ModBlocks.MANGANESE_ORE.block().get(), "Manganese Ore");
        add(ModBlocks.MOLYBDENUM_ORE.block().get(), "Molybdenum Ore");
        add(ModBlocks.NICKEL_ORE.block().get(), "Nickel Ore");
        add(ModBlocks.NIOBIUM_ORE.block().get(), "Niobium Ore");
        add(ModBlocks.OSMIUM_ORE.block().get(), "Osmium Ore");
        add(ModBlocks.PALLADIUM_ORE.block().get(), "Palladium Ore");
        add(ModBlocks.PHOSPHORUS_ORE.block().get(), "Phosphorus Ore");
        add(ModBlocks.PLATINUM_ORE.block().get(), "Platinum Ore");
        add(ModBlocks.POTASSIUM_ORE.block().get(), "Potassium Ore");
        add(ModBlocks.RHENIUM_ORE.block().get(), "Rhenium Ore");
        add(ModBlocks.RHODIUM_ORE.block().get(), "Rhodium Ore");
        add(ModBlocks.RUBIDIUM_ORE.block().get(), "Rubidium Ore");
        add(ModBlocks.RUTHENIUM_ORE.block().get(), "Ruthenium Ore");
        add(ModBlocks.SCANDIUM_ORE.block().get(), "Scandium Ore");
        add(ModBlocks.SELENIUM_ORE.block().get(), "Selenium Ore");
        add(ModBlocks.SILICON_ORE.block().get(), "Silicon Ore");
        add(ModBlocks.SILVER_ORE.block().get(), "Silver Ore");
        add(ModBlocks.SODIUM_ORE.block().get(), "Sodium Ore");
        add(ModBlocks.STRONTIUM_ORE.block().get(), "Strontium Ore");
        add(ModBlocks.TANTALUM_ORE.block().get(), "Tantalum Ore");
        add(ModBlocks.TECHNETIUM_ORE.block().get(), "Technetium Ore");
        add(ModBlocks.TELLURIUM_ORE.block().get(), "Tellurium Ore");
        add(ModBlocks.THALLIUM_ORE.block().get(), "Thallium Ore");
        add(ModBlocks.TIN_ORE.block().get(), "Tin Ore");
        add(ModBlocks.TITANIUM_ORE.block().get(), "Titanium Ore");
        add(ModBlocks.TUNGSTEN_ORE.block().get(), "Tungsten Ore");
        add(ModBlocks.VANADIUM_ORE.block().get(), "Vanadium Ore");
        add(ModBlocks.YTTRIUM_ORE.block().get(), "Yttrium Ore");
        add(ModBlocks.ZINC_ORE.block().get(), "Zinc Ore");
        add(ModBlocks.ZIRCONIUM_ORE.block().get(), "Zirconium Ore");

        //Blocks - Block
        add(ModBlocks.ALUMINIUM_BLOCK.block().get(), "Block of Aluminium");
        add(ModBlocks.ANTIMONY_BLOCK.block().get(), "Block of Antimony");
        add(ModBlocks.ARSENIC_BLOCK.block().get(), "Block of Arsenic");
        add(ModBlocks.BARIUM_BLOCK.block().get(), "Block of Barium");
        add(ModBlocks.BERYLLIUM_BLOCK.block().get(), "Block of Beryllium");
        add(ModBlocks.BISMUTH_BLOCK.block().get(), "Block of Bismuth");
        add(ModBlocks.CADMIUM_BLOCK.block().get(), "Block of Cadmium");
        add(ModBlocks.CALCIUM_BLOCK.block().get(), "Block of Calcium");
        add(ModBlocks.CAESIUM_BLOCK.block().get(), "Block of Caesium");
        add(ModBlocks.CHROMIUM_BLOCK.block().get(), "Block of Chromium");
        add(ModBlocks.CINNABAR_BLOCK.block().get(), "Block of Mercury");
        add(ModBlocks.COBALT_BLOCK.block().get(), "Block of Cobalt");
        add(ModBlocks.GERMANIUM_BLOCK.block().get(), "Block of Germanium");
        add(ModBlocks.GALLIUM_BLOCK.block().get(), "Block of Gallium");
        add(ModBlocks.HAFNIUM_BLOCK.block().get(), "Block of Hafnium");
        add(ModBlocks.INDIUM_BLOCK.block().get(), "Block of Indium");
        add(ModBlocks.IRIDIUM_BLOCK.block().get(), "Block of Iridium");
        add(ModBlocks.LEAD_BLOCK.block().get(), "Block of Lead");
        add(ModBlocks.LITHIUM_BLOCK.block().get(), "Block of Lithium");
        add(ModBlocks.MAGNESIUM_BLOCK.block().get(), "Block of Magnesium");
        add(ModBlocks.MANGANESE_BLOCK.block().get(), "Block of Manganese");
        add(ModBlocks.MOLYBDENUM_BLOCK.block().get(), "Block of Molybdenum");
        add(ModBlocks.NICKEL_BLOCK.block().get(), "Block of Nickel");
        add(ModBlocks.NIOBIUM_BLOCK.block().get(), "Block of Niobium");
        add(ModBlocks.OSMIUM_BLOCK.block().get(), "Block of Osmium");
        add(ModBlocks.PALLADIUM_BLOCK.block().get(), "Block of Palladium");
        add(ModBlocks.PHOSPHORUS_BLOCK.block().get(), "Block of Phosphorus");
        add(ModBlocks.PLATINUM_BLOCK.block().get(), "Block of Platinum");
        add(ModBlocks.POTASSIUM_BLOCK.block().get(), "Block of Potassium");
        add(ModBlocks.RHENIUM_BLOCK.block().get(), "Block of Rhenium");
        add(ModBlocks.RHODIUM_BLOCK.block().get(), "Block of Rhodium");
        add(ModBlocks.RUBIDIUM_BLOCK.block().get(), "Block of Rubidium");
        add(ModBlocks.RUTHENIUM_BLOCK.block().get(), "Block of Ruthenium");
        add(ModBlocks.SCANDIUM_BLOCK.block().get(), "Block of Scandium");
        add(ModBlocks.SELENIUM_BLOCK.block().get(), "Block of Selenium");
        add(ModBlocks.SILICON_BLOCK.block().get(), "Block of Silicon");
        add(ModBlocks.SILVER_BLOCK.block().get(), "Block of Silver");
        add(ModBlocks.SODIUM_BLOCK.block().get(), "Block of Sodium");
        add(ModBlocks.STRONTIUM_BLOCK.block().get(), "Block of Strontium");
        add(ModBlocks.TANTALUM_BLOCK.block().get(), "Block of Tantalum");
        add(ModBlocks.TECHNETIUM_BLOCK.block().get(), "Block of Technetium");
        add(ModBlocks.TELLURIUM_BLOCK.block().get(), "Block of Tellurium");
        add(ModBlocks.THALLIUM_BLOCK.block().get(), "Block of Thallium");
        add(ModBlocks.TIN_BLOCK.block().get(), "Block of Tin");
        add(ModBlocks.TITANIUM_BLOCK.block().get(), "Block of Titanium");
        add(ModBlocks.TUNGSTEN_BLOCK.block().get(), "Block of Tungsten");
        add(ModBlocks.VANADIUM_BLOCK.block().get(), "Block of Vanadium");
        add(ModBlocks.YTTRIUM_BLOCK.block().get(), "Block of Yttrium");
        add(ModBlocks.ZINC_BLOCK.block().get(), "Block of Zinc");
        add(ModBlocks.ZIRCONIUM_BLOCK.block().get(), "Block of Zirconium");


        //Blocks - Raw Block
        add(ModBlocks.RAW_ALUMINIUM_BLOCK.block().get(), "Block of Raw Aluminium");
        add(ModBlocks.RAW_ANTIMONY_BLOCK.block().get(), "Block of Raw Antimony");
        add(ModBlocks.RAW_ARSENIC_BLOCK.block().get(), "Block of Raw Arsenic");
        add(ModBlocks.RAW_BARIUM_BLOCK.block().get(), "Block of Raw Barium");
        add(ModBlocks.RAW_BERYLLIUM_BLOCK.block().get(), "Block of Raw Beryllium");
        add(ModBlocks.RAW_BISMUTH_BLOCK.block().get(), "Block of Raw Bismuth");
        add(ModBlocks.RAW_CADMIUM_BLOCK.block().get(), "Block of Raw Cadmium");
        add(ModBlocks.RAW_CALCIUM_BLOCK.block().get(), "Block of Raw Calcium");
        add(ModBlocks.RAW_CAESIUM_BLOCK.block().get(), "Block of Raw Caesium");
        add(ModBlocks.RAW_CHROMIUM_BLOCK.block().get(), "Block of Raw Chromium");
        add(ModBlocks.RAW_CINNABAR_BLOCK.block().get(), "Block of Raw Mercury");
        add(ModBlocks.RAW_COBALT_BLOCK.block().get(), "Block of Raw Cobalt");
        add(ModBlocks.RAW_GERMANIUM_BLOCK.block().get(), "Block of Raw Germanium");
        add(ModBlocks.RAW_GALLIUM_BLOCK.block().get(), "Block of Raw Gallium");
        add(ModBlocks.RAW_HAFNIUM_BLOCK.block().get(), "Block of Raw Hafnium");
        add(ModBlocks.RAW_INDIUM_BLOCK.block().get(), "Block of Raw Indium");
        add(ModBlocks.RAW_IRIDIUM_BLOCK.block().get(), "Block of Raw Iridium");
        add(ModBlocks.RAW_LEAD_BLOCK.block().get(), "Block of Raw Lead");
        add(ModBlocks.RAW_LITHIUM_BLOCK.block().get(), "Block of Raw Lithium");
        add(ModBlocks.RAW_MAGNESIUM_BLOCK.block().get(), "Block of Raw Magnesium");
        add(ModBlocks.RAW_MANGANESE_BLOCK.block().get(), "Block of Raw Manganese");
        add(ModBlocks.RAW_MOLYBDENUM_BLOCK.block().get(), "Block of Raw Molybdenum");
        add(ModBlocks.RAW_NICKEL_BLOCK.block().get(), "Block of Raw Nickel");
        add(ModBlocks.RAW_NIOBIUM_BLOCK.block().get(), "Block of Raw Niobium");
        add(ModBlocks.RAW_OSMIUM_BLOCK.block().get(), "Block of Raw Osmium");
        add(ModBlocks.RAW_PALLADIUM_BLOCK.block().get(), "Block of Raw Palladium");
        add(ModBlocks.RAW_PHOSPHORUS_BLOCK.block().get(), "Block of Raw Phosphorus");
        add(ModBlocks.RAW_PLATINUM_BLOCK.block().get(), "Block of Raw Platinum");
        add(ModBlocks.RAW_POTASSIUM_BLOCK.block().get(), "Block of Raw Potassium");
        add(ModBlocks.RAW_RHENIUM_BLOCK.block().get(), "Block of Raw Rhenium");
        add(ModBlocks.RAW_RHODIUM_BLOCK.block().get(), "Block of Raw Rhodium");
        add(ModBlocks.RAW_RUBIDIUM_BLOCK.block().get(), "Block of Raw Rubidium");
        add(ModBlocks.RAW_RUTHENIUM_BLOCK.block().get(), "Block of Raw Ruthenium");
        add(ModBlocks.RAW_SCANDIUM_BLOCK.block().get(), "Block of Raw Scandium");
        add(ModBlocks.RAW_SELENIUM_BLOCK.block().get(), "Block of Raw Selenium");
        add(ModBlocks.RAW_SILICON_BLOCK.block().get(), "Block of Raw Silicon");
        add(ModBlocks.RAW_SILVER_BLOCK.block().get(), "Block of Raw Silver");
        add(ModBlocks.RAW_SODIUM_BLOCK.block().get(), "Block of Raw Sodium");
        add(ModBlocks.RAW_STRONTIUM_BLOCK.block().get(), "Block of Raw Strontium");
        add(ModBlocks.RAW_TANTALUM_BLOCK.block().get(), "Block of Raw Tantalum");
        add(ModBlocks.RAW_TECHNETIUM_BLOCK.block().get(), "Block of Raw Technetium");
        add(ModBlocks.RAW_TELLURIUM_BLOCK.block().get(), "Block of Raw Tellurium");
        add(ModBlocks.RAW_THALLIUM_BLOCK.block().get(), "Block of Raw Thallium");
        add(ModBlocks.RAW_TIN_BLOCK.block().get(), "Block of Raw Tin");
        add(ModBlocks.RAW_TITANIUM_BLOCK.block().get(), "Block of Raw Titanium");
        add(ModBlocks.RAW_TUNGSTEN_BLOCK.block().get(), "Block of Raw Tungsten");
        add(ModBlocks.RAW_VANADIUM_BLOCK.block().get(), "Block of Raw Vanadium");
        add(ModBlocks.RAW_YTTRIUM_BLOCK.block().get(), "Block of Raw Yttrium");
        add(ModBlocks.RAW_ZINC_BLOCK.block().get(), "Block of Raw Zinc");
        add(ModBlocks.RAW_ZIRCONIUM_BLOCK.block().get(), "Block of Raw Zirconium");

        //ItemBlocks - Ore
        add(ModBlocks.ALUMINIUM_ORE.item().get(), "Aluminium Ore");
        add(ModBlocks.ANTIMONY_ORE.item().get(), "Antimony Ore");
        add(ModBlocks.ARSENIC_ORE.item().get(), "Arsenic Ore");
        add(ModBlocks.BARIUM_ORE.item().get(), "Barium Ore");
        add(ModBlocks.BERYLLIUM_ORE.item().get(), "Beryllium Ore");
        add(ModBlocks.BISMUTH_ORE.item().get(), "Bismuth Ore");
        add(ModBlocks.CADMIUM_ORE.item().get(), "Cadmium Ore");
        add(ModBlocks.CALCIUM_ORE.item().get(), "Calcium Ore");
        add(ModBlocks.CAESIUM_ORE.item().get(), "Caesium Ore");
        add(ModBlocks.CHROMIUM_ORE.item().get(), "Chromium Ore");
        add(ModBlocks.CINNABAR_ORE.item().get(), "Mercury Ore");
        add(ModBlocks.COBALT_ORE.item().get(), "Cobalt Ore");
        add(ModBlocks.GERMANIUM_ORE.item().get(), "Germanium Ore");
        add(ModBlocks.GALLIUM_ORE.item().get(), "Gallium Ore");
        add(ModBlocks.HAFNIUM_ORE.item().get(), "Hafnium Ore");
        add(ModBlocks.INDIUM_ORE.item().get(), "Indium Ore");
        add(ModBlocks.IRIDIUM_ORE.item().get(), "Iridium Ore");
        add(ModBlocks.LEAD_ORE.item().get(), "Lead Ore");
        add(ModBlocks.LITHIUM_ORE.item().get(), "Lithium Ore");
        add(ModBlocks.MAGNESIUM_ORE.item().get(), "Magnesium Ore");
        add(ModBlocks.MANGANESE_ORE.item().get(), "Manganese Ore");
        add(ModBlocks.MOLYBDENUM_ORE.item().get(), "Molybdenum Ore");
        add(ModBlocks.NICKEL_ORE.item().get(), "Nickel Ore");
        add(ModBlocks.NIOBIUM_ORE.item().get(), "Niobium Ore");
        add(ModBlocks.OSMIUM_ORE.item().get(), "Osmium Ore");
        add(ModBlocks.PALLADIUM_ORE.item().get(), "Palladium Ore");
        add(ModBlocks.PHOSPHORUS_ORE.item().get(), "Phosphorus Ore");
        add(ModBlocks.PLATINUM_ORE.item().get(), "Platinum Ore");
        add(ModBlocks.POTASSIUM_ORE.item().get(), "Potassium Ore");
        add(ModBlocks.RHENIUM_ORE.item().get(), "Rhenium Ore");
        add(ModBlocks.RHODIUM_ORE.item().get(), "Rhodium Ore");
        add(ModBlocks.RUBIDIUM_ORE.item().get(), "Rubidium Ore");
        add(ModBlocks.RUTHENIUM_ORE.item().get(), "Ruthenium Ore");
        add(ModBlocks.SCANDIUM_ORE.item().get(), "Scandium Ore");
        add(ModBlocks.SELENIUM_ORE.item().get(), "Selenium Ore");
        add(ModBlocks.SILICON_ORE.item().get(), "Silicon Ore");
        add(ModBlocks.SILVER_ORE.item().get(), "Silver Ore");
        add(ModBlocks.SODIUM_ORE.item().get(), "Sodium Ore");
        add(ModBlocks.STRONTIUM_ORE.item().get(), "Strontium Ore");
        add(ModBlocks.TANTALUM_ORE.item().get(), "Tantalum Ore");
        add(ModBlocks.TECHNETIUM_ORE.item().get(), "Technetium Ore");
        add(ModBlocks.TELLURIUM_ORE.item().get(), "Tellurium Ore");
        add(ModBlocks.THALLIUM_ORE.item().get(), "Thallium Ore");
        add(ModBlocks.TIN_ORE.item().get(), "Tin Ore");
        add(ModBlocks.TITANIUM_ORE.item().get(), "Titanium Ore");
        add(ModBlocks.TUNGSTEN_ORE.item().get(), "Tungsten Ore");
        add(ModBlocks.VANADIUM_ORE.item().get(), "Vanadium Ore");
        add(ModBlocks.YTTRIUM_ORE.item().get(), "Yttrium Ore");
        add(ModBlocks.ZINC_ORE.item().get(), "Zinc Ore");
        add(ModBlocks.ZIRCONIUM_ORE.item().get(), "Zirconium Ore");

        //ItemBlocks - Block
        add(ModBlocks.ALUMINIUM_BLOCK.item().get(), "Block of Aluminium");
        add(ModBlocks.ANTIMONY_BLOCK.item().get(), "Block of Antimony");
        add(ModBlocks.ARSENIC_BLOCK.item().get(), "Block of Arsenic");
        add(ModBlocks.BARIUM_BLOCK.item().get(), "Block of Barium");
        add(ModBlocks.BERYLLIUM_BLOCK.item().get(), "Block of Beryllium");
        add(ModBlocks.BISMUTH_BLOCK.item().get(), "Block of Bismuth");
        add(ModBlocks.CADMIUM_BLOCK.item().get(), "Block of Cadmium");
        add(ModBlocks.CALCIUM_BLOCK.item().get(), "Block of Calcium");
        add(ModBlocks.CAESIUM_BLOCK.item().get(), "Block of Caesium");
        add(ModBlocks.CHROMIUM_BLOCK.item().get(), "Block of Chromium");
        add(ModBlocks.CINNABAR_BLOCK.item().get(), "Block of Mercury");
        add(ModBlocks.COBALT_BLOCK.item().get(), "Block of Cobalt");
        add(ModBlocks.GERMANIUM_BLOCK.item().get(), "Block of Germanium");
        add(ModBlocks.GALLIUM_BLOCK.item().get(), "Block of Gallium");
        add(ModBlocks.HAFNIUM_BLOCK.item().get(), "Block of Hafnium");
        add(ModBlocks.INDIUM_BLOCK.item().get(), "Block of Indium");
        add(ModBlocks.IRIDIUM_BLOCK.item().get(), "Block of Iridium");
        add(ModBlocks.LEAD_BLOCK.item().get(), "Block of Lead");
        add(ModBlocks.LITHIUM_BLOCK.item().get(), "Block of Lithium");
        add(ModBlocks.MAGNESIUM_BLOCK.item().get(), "Block of Magnesium");
        add(ModBlocks.MANGANESE_BLOCK.item().get(), "Block of Manganese");
        add(ModBlocks.MOLYBDENUM_BLOCK.item().get(), "Block of Molybdenum");
        add(ModBlocks.NICKEL_BLOCK.item().get(), "Block of Nickel");
        add(ModBlocks.NIOBIUM_BLOCK.item().get(), "Block of Niobium");
        add(ModBlocks.OSMIUM_BLOCK.item().get(), "Block of Osmium");
        add(ModBlocks.PALLADIUM_BLOCK.item().get(), "Block of Palladium");
        add(ModBlocks.PHOSPHORUS_BLOCK.item().get(), "Block of Phosphorus");
        add(ModBlocks.PLATINUM_BLOCK.item().get(), "Block of Platinum");
        add(ModBlocks.POTASSIUM_BLOCK.item().get(), "Block of Potassium");
        add(ModBlocks.RHENIUM_BLOCK.item().get(), "Block of Rhenium");
        add(ModBlocks.RHODIUM_BLOCK.item().get(), "Block of Rhodium");
        add(ModBlocks.RUBIDIUM_BLOCK.item().get(), "Block of Rubidium");
        add(ModBlocks.RUTHENIUM_BLOCK.item().get(), "Block of Ruthenium");
        add(ModBlocks.SCANDIUM_BLOCK.item().get(), "Block of Scandium");
        add(ModBlocks.SELENIUM_BLOCK.item().get(), "Block of Selenium");
        add(ModBlocks.SILICON_BLOCK.item().get(), "Block of Silicon");
        add(ModBlocks.SILVER_BLOCK.item().get(), "Block of Silver");
        add(ModBlocks.SODIUM_BLOCK.item().get(), "Block of Sodium");
        add(ModBlocks.STRONTIUM_BLOCK.item().get(), "Block of Strontium");
        add(ModBlocks.TANTALUM_BLOCK.item().get(), "Block of Tantalum");
        add(ModBlocks.TECHNETIUM_BLOCK.item().get(), "Block of Technetium");
        add(ModBlocks.TELLURIUM_BLOCK.item().get(), "Block of Tellurium");
        add(ModBlocks.THALLIUM_BLOCK.item().get(), "Block of Thallium");
        add(ModBlocks.TIN_BLOCK.item().get(), "Block of Tin");
        add(ModBlocks.TITANIUM_BLOCK.item().get(), "Block of Titanium");
        add(ModBlocks.TUNGSTEN_BLOCK.item().get(), "Block of Tungsten");
        add(ModBlocks.VANADIUM_BLOCK.item().get(), "Block of Vanadium");
        add(ModBlocks.YTTRIUM_BLOCK.item().get(), "Block of Yttrium");
        add(ModBlocks.ZINC_BLOCK.item().get(), "Block of Zinc");
        add(ModBlocks.ZIRCONIUM_BLOCK.item().get(), "Block of Zirconium");

        //ItemBlocks - Raw Block
        add(ModBlocks.RAW_ALUMINIUM_BLOCK.item().get(), "Block of Raw Aluminium");
        add(ModBlocks.RAW_ANTIMONY_BLOCK.item().get(), "Block of Raw Antimony");
        add(ModBlocks.RAW_ARSENIC_BLOCK.item().get(), "Block of Raw Arsenic");
        add(ModBlocks.RAW_BARIUM_BLOCK.item().get(), "Block of Raw Barium");
        add(ModBlocks.RAW_BERYLLIUM_BLOCK.item().get(), "Block of Raw Beryllium");
        add(ModBlocks.RAW_BISMUTH_BLOCK.item().get(), "Block of Raw Bismuth");
        add(ModBlocks.RAW_CADMIUM_BLOCK.item().get(), "Block of Raw Cadmium");
        add(ModBlocks.RAW_CALCIUM_BLOCK.item().get(), "Block of Raw Calcium");
        add(ModBlocks.RAW_CAESIUM_BLOCK.item().get(), "Block of Raw Caesium");
        add(ModBlocks.RAW_CHROMIUM_BLOCK.item().get(), "Block of Raw Chromium");
        add(ModBlocks.RAW_CINNABAR_BLOCK.item().get(), "Block of Raw Mercury");
        add(ModBlocks.RAW_COBALT_BLOCK.item().get(), "Block of Raw Cobalt");
        add(ModBlocks.RAW_GERMANIUM_BLOCK.item().get(), "Block of Raw Germanium");
        add(ModBlocks.RAW_GALLIUM_BLOCK.item().get(), "Block of Raw Gallium");
        add(ModBlocks.RAW_HAFNIUM_BLOCK.item().get(), "Block of Raw Hafnium");
        add(ModBlocks.RAW_INDIUM_BLOCK.item().get(), "Block of Raw Indium");
        add(ModBlocks.RAW_IRIDIUM_BLOCK.item().get(), "Block of Raw Iridium");
        add(ModBlocks.RAW_LEAD_BLOCK.item().get(), "Block of Raw Lead");
        add(ModBlocks.RAW_LITHIUM_BLOCK.item().get(), "Block of Raw Lithium");
        add(ModBlocks.RAW_MAGNESIUM_BLOCK.item().get(), "Block of Raw Magnesium");
        add(ModBlocks.RAW_MANGANESE_BLOCK.item().get(), "Block of Raw Manganese");
        add(ModBlocks.RAW_MOLYBDENUM_BLOCK.item().get(), "Block of Raw Molybdenum");
        add(ModBlocks.RAW_NICKEL_BLOCK.item().get(), "Block of Raw Nickel");
        add(ModBlocks.RAW_NIOBIUM_BLOCK.item().get(), "Block of Raw Niobium");
        add(ModBlocks.RAW_OSMIUM_BLOCK.item().get(), "Block of Raw Osmium");
        add(ModBlocks.RAW_PALLADIUM_BLOCK.item().get(), "Block of Raw Palladium");
        add(ModBlocks.RAW_PHOSPHORUS_BLOCK.item().get(), "Block of Raw Phosphorus");
        add(ModBlocks.RAW_PLATINUM_BLOCK.item().get(), "Block of Raw Platinum");
        add(ModBlocks.RAW_POTASSIUM_BLOCK.item().get(), "Block of Raw Potassium");
        add(ModBlocks.RAW_RHENIUM_BLOCK.item().get(), "Block of Raw Rhenium");
        add(ModBlocks.RAW_RHODIUM_BLOCK.item().get(), "Block of Raw Rhodium");
        add(ModBlocks.RAW_RUBIDIUM_BLOCK.item().get(), "Block of Raw Rubidium");
        add(ModBlocks.RAW_RUTHENIUM_BLOCK.item().get(), "Block of Raw Ruthenium");
        add(ModBlocks.RAW_SCANDIUM_BLOCK.item().get(), "Block of Raw Scandium");
        add(ModBlocks.RAW_SELENIUM_BLOCK.item().get(), "Block of Raw Selenium");
        add(ModBlocks.RAW_SILICON_BLOCK.item().get(), "Block of Raw Silicon");
        add(ModBlocks.RAW_SILVER_BLOCK.item().get(), "Block of Raw Silver");
        add(ModBlocks.RAW_SODIUM_BLOCK.item().get(), "Block of Raw Sodium");
        add(ModBlocks.RAW_STRONTIUM_BLOCK.item().get(), "Block of Raw Strontium");
        add(ModBlocks.RAW_TANTALUM_BLOCK.item().get(), "Block of Raw Tantalum");
        add(ModBlocks.RAW_TECHNETIUM_BLOCK.item().get(), "Block of Raw Technetium");
        add(ModBlocks.RAW_TELLURIUM_BLOCK.item().get(), "Block of Raw Tellurium");
        add(ModBlocks.RAW_THALLIUM_BLOCK.item().get(), "Block of Raw Thallium");
        add(ModBlocks.RAW_TIN_BLOCK.item().get(), "Block of Raw Tin");
        add(ModBlocks.RAW_TITANIUM_BLOCK.item().get(), "Block of Raw Titanium");
        add(ModBlocks.RAW_TUNGSTEN_BLOCK.item().get(), "Block of Raw Tungsten");
        add(ModBlocks.RAW_VANADIUM_BLOCK.item().get(), "Block of Raw Vanadium");
        add(ModBlocks.RAW_YTTRIUM_BLOCK.item().get(), "Block of Raw Yttrium");
        add(ModBlocks.RAW_ZINC_BLOCK.item().get(), "Block of Raw Zinc");
        add(ModBlocks.RAW_ZIRCONIUM_BLOCK.item().get(), "Block of Raw Zirconium");

        //Tools and Armor
        add(ModItems.ALUMINIUM_SWORD.get(),"Aluminium Sword");
        add(ModItems.ALUMINIUM_PICKAXE.get(),"Aluminium Pickaxe");
        add(ModItems.ALUMINIUM_SHOVEL.get(),"Aluminium Shovel");
        add(ModItems.ALUMINIUM_AXE.get(),"Aluminium Axe");
        add(ModItems.ALUMINIUM_HOE.get(),"Aluminium Hoe");
        add(ModItems.ALUMINIUM_HELMET.get(),"Aluminium Helmet");
        add(ModItems.ALUMINIUM_CHESTPLATE.get(),"Aluminium Chestplate");
        add(ModItems.ALUMINIUM_LEGGINGS.get(),"Aluminium Leggings");
        add(ModItems.ALUMINIUM_BOOTS.get(),"Aluminium Boots");

        add(ModItems.SILVER_SWORD.get(),"Silver Sword");
        add(ModItems.SILVER_PICKAXE.get(),"Silver Pickaxe");
        add(ModItems.SILVER_SHOVEL.get(),"Silver Shovel");
        add(ModItems.SILVER_AXE.get(),"Silver Axe");
        add(ModItems.SILVER_HOE.get(),"Silver Hoe");
        add(ModItems.SILVER_HELMET.get(),"Silver Pickaxe");
        add(ModItems.SILVER_CHESTPLATE.get(),"Silver Shovel");
        add(ModItems.SILVER_LEGGINGS.get(),"Silver Axe");
        add(ModItems.SILVER_BOOTS.get(),"Silver Hoe");

        add(ModItems.TECHNETIUM_SWORD.get(),"Technetium Sword");
        add(ModItems.TECHNETIUM_PICKAXE.get(),"Technetium Pickaxe");
        add(ModItems.TECHNETIUM_SHOVEL.get(),"Technetium Shovel");
        add(ModItems.TECHNETIUM_AXE.get(),"Technetium Axe");
        add(ModItems.TECHNETIUM_HOE.get(),"Technetium Hoe");
        add(ModItems.TECHNETIUM_HELMET.get(),"Technetium Helmet");
        add(ModItems.TECHNETIUM_CHESTPLATE.get(),"Technetium Chestplate");
        add(ModItems.TECHNETIUM_LEGGINGS.get(),"Technetium Leggings");
        add(ModItems.TECHNETIUM_BOOTS.get(),"Technetium Boots");

        add(ModItems.TITANIUM_SWORD.get(),"Titanium Sword");
        add(ModItems.TITANIUM_PICKAXE.get(),"Titanium Pickaxe");
        add(ModItems.TITANIUM_SHOVEL.get(),"Titanium Shovel");
        add(ModItems.TITANIUM_AXE.get(),"Titanium Axe");
        add(ModItems.TITANIUM_HOE.get(),"Titanium Hoe");
        add(ModItems.TITANIUM_HELMET.get(),"Titanium Helmet");
        add(ModItems.TITANIUM_CHESTPLATE.get(),"Titanium Chestplate");
        add(ModItems.TITANIUM_LEGGINGS.get(),"Titanium Leggings");
        add(ModItems.TITANIUM_BOOTS.get(),"Titanium Boots");

        add(ModItems.FABRIC_STRAP.get(), "Fabric Strap");
        add(ModItems.FABRIC_GRIP.get(), "Fabric-Wrapped Grip");

        add(ModItems.LEATHER_STRAP.get(), "Leather Strap");
        add(ModItems.LEATHER_GRIP.get(), "Leather-Wrapped Grip");

        add(ModItems.ARMOUR_PADDING.get(), "Armour Padding");

        add(ModItems.ALUMINIUM_BLADE.get(), "Aluminium Blade");
        add(ModItems.ALUMINIUM_AXEHEAD.get(), "Aluminium Axe Head");
        add(ModItems.ALUMINIUM_GUARD.get(), "Aluminium Rain-Guard");
        add(ModItems.ALUMINIUM_SHOVELHEAD.get(), "Aluminium Shovel Head");
        add(ModItems.ALUMINIUM_PICK.get(), "Aluminium Pick");
        add(ModItems.ALUMINIUM_POMMEL.get(), "Aluminium Pommel");
        add(ModItems.ALUMINIUM_PLATE.get(), "Aluminium Armour Plate");
        add(ModItems.ALUMINIUM_HILT.get(), "Aluminium-Pommelled Hilt");

        add(ModItems.SILVER_BLADE.get(), "Silver Blade");
        add(ModItems.SILVER_AXEHEAD.get(), "Silver Axe Head");
        add(ModItems.SILVER_GUARD.get(), "Silver Rain-Guard");
        add(ModItems.SILVER_SHOVELHEAD.get(), "Sliver Shovel Head");
        add(ModItems.SILVER_PICK.get(), "Silver Pick");
        add(ModItems.SILVER_POMMEL.get(), "Silver Pommel");
        add(ModItems.SILVER_PLATE.get(), "Silver Armour Plate");
        add(ModItems.SILVER_HILT.get(), "Silver-Pommelled Hilt");

        add(ModItems.TECHNETIUM_BLADE.get(), "Technetium Blade");
        add(ModItems.TECHNETIUM_AXEHEAD.get(), "Technetium Axe Head");
        add(ModItems.TECHNETIUM_GUARD.get(), "Technetium Rain-Guard");
        add(ModItems.TECHNETIUM_SHOVELHEAD.get(), "Technetium Shovel Head");
        add(ModItems.TECHNETIUM_PICK.get(), "Technetium Pick");
        add(ModItems.TECHNETIUM_POMMEL.get(), "Technetium Pommel");
        add(ModItems.TECHNETIUM_PLATE.get(), "Technetium Armour Plate");
        add(ModItems.TECHNETIUM_HILT.get(), "Technetium-Pommelled Hilt");

        add(ModItems.TITANIUM_BLADE.get(), "Titanium Blade");
        add(ModItems.TITANIUM_AXEHEAD.get(), "Titanium Axe Head");
        add(ModItems.TITANIUM_SHOVELHEAD.get(), "Titanium Shovel Head");
        add(ModItems.TITANIUM_PICK.get(), "Titanium Pick");
        add(ModItems.TITANIUM_POMMEL.get(), "Titanium Pommel");
        add(ModItems.TITANIUM_GUARD.get(), "Titanium Rain-Guard");
        add(ModItems.TITANIUM_PLATE.get(), "Titanium Armour Plate");
        add(ModItems.TITANIUM_HILT.get(), "Titanium-Pommelled Hilt");

        add(ModCreativeTabs.MEGALOS_AIO_TAB.get().getDisplayName(), "Megalo's AIO");
    }

    private void add(Component component, String value){
        if (component.getContents() instanceof TranslatableContents translatableContents){
            add(translatableContents.getKey(), value);
        }
    }
}
