package com.megalogaminguk.megalosaio.datagen;

import com.megalogaminguk.megalosaio.Constants;
import com.megalogaminguk.megalosaio.init.ModBlocks;
import com.megalogaminguk.megalosaio.init.ModItems;
import net.minecraft.client.data.models.BlockModelGenerators;
import net.minecraft.client.data.models.ItemModelGenerators;
import net.minecraft.client.data.models.ModelProvider;
import net.minecraft.client.data.models.model.ModelTemplates;
import net.minecraft.data.PackOutput;

public class MegalosAIOModelProvider extends ModelProvider {
    public MegalosAIOModelProvider(PackOutput output) {
        super(output, Constants.MOD_ID);
    }

    @Override
    protected void registerModels(BlockModelGenerators blockModels, ItemModelGenerators itemModels){
        //Items******

        //Items - Ingot
        itemModels.generateFlatItem(ModItems.ALUMINIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ANTIMONY_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ARSENIC_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.BARIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.BERYLLIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.BISMUTH_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.CADMIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.CALCIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.CAESIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.CHROMIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.CINNABAR_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.COBALT_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.GERMANIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.GALLIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.HAFNIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.INDIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.IRIDIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.LEAD_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.LITHIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.MAGNESIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.MANGANESE_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.MOLYBDENUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.NICKEL_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.NIOBIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.OSMIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.PALLADIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.PHOSPHORUS_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.PLATINUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.POTASSIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RHENIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RHODIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RUBIDIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RUTHENIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SCANDIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SELENIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SILICON_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SILVER_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SODIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.STRONTIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TANTALUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TECHNETIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TELLURIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.THALLIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TIN_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TITANIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TUNGSTEN_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.VANADIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.YTTRIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ZINC_INGOT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ZIRCONIUM_INGOT.get(), ModelTemplates.FLAT_ITEM);

        //Items - Nugget
        itemModels.generateFlatItem(ModItems.ALUMINIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ANTIMONY_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ARSENIC_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.BARIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.BERYLLIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.BISMUTH_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.CADMIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.CALCIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.CAESIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.CHROMIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.CINNABAR_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.COBALT_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.GERMANIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.GALLIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.HAFNIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.INDIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.IRIDIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.LEAD_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.LITHIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.MAGNESIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.MANGANESE_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.MOLYBDENUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.NICKEL_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.NIOBIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.OSMIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.PALLADIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.PHOSPHORUS_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.PLATINUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.POTASSIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RHENIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RHODIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RUBIDIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RUTHENIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SCANDIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SELENIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SILICON_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SILVER_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SODIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.STRONTIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TANTALUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TECHNETIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TELLURIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.THALLIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TIN_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TITANIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TUNGSTEN_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.VANADIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.YTTRIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ZINC_NUGGET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ZIRCONIUM_NUGGET.get(), ModelTemplates.FLAT_ITEM);

        //Items - Dust
        itemModels.generateFlatItem(ModItems.ALUMINIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ANTIMONY_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ARSENIC_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.BARIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.BERYLLIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.BISMUTH_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.CADMIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.CALCIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.CAESIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.CHROMIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.CINNABAR_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.COBALT_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.GERMANIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.GALLIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.HAFNIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.INDIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.IRIDIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.LEAD_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.LITHIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.MAGNESIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.MANGANESE_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.MOLYBDENUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.NICKEL_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.NIOBIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.OSMIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.PALLADIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.PHOSPHORUS_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.PLATINUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.POTASSIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RHENIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RHODIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RUBIDIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RUTHENIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SCANDIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SELENIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SILICON_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SILVER_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SODIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.STRONTIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TANTALUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TECHNETIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TELLURIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.THALLIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TIN_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TITANIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TUNGSTEN_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.VANADIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.YTTRIUM_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ZINC_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ZIRCONIUM_DUST.get(), ModelTemplates.FLAT_ITEM);

        //Items - Raw
        itemModels.generateFlatItem(ModItems.RAW_ALUMINIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_ANTIMONY.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_ARSENIC.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_BARIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_BERYLLIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_BISMUTH.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_CADMIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_CALCIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_CAESIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_CHROMIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_CINNABAR.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_COBALT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_GERMANIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_GALLIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_HAFNIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_INDIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_IRIDIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_LEAD.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_LITHIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_MAGNESIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_MANGANESE.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_MOLYBDENUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_NICKEL.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_NIOBIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_OSMIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_PALLADIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_PHOSPHORUS.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_PLATINUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_POTASSIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_RHENIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_RHODIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_RUBIDIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_RUTHENIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_SCANDIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_SELENIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_SILICON.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_SILVER.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_SODIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_STRONTIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_TANTALUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_TECHNETIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_TELLURIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_THALLIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_TIN.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_TITANIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_TUNGSTEN.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_VANADIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_YTTRIUM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_ZINC.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.RAW_ZIRCONIUM.get(), ModelTemplates.FLAT_ITEM);

        //Vanilla - Dust
        itemModels.generateFlatItem(ModItems.COPPER_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.IRON_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.GOLD_DUST.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.COAL_DUST.get(), ModelTemplates.FLAT_ITEM);

        //Blocks******

        //Blocks - Ore
        blockModels.createTrivialCube(ModBlocks.ALUMINIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.ANTIMONY_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.ARSENIC_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.BARIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.BERYLLIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.BISMUTH_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.CADMIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.CALCIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.CAESIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.CHROMIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.CINNABAR_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.COBALT_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.GERMANIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.GALLIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.HAFNIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.INDIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.IRIDIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.LEAD_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.LITHIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.MAGNESIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.MANGANESE_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.MOLYBDENUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.NICKEL_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.NIOBIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.OSMIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.PALLADIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.PHOSPHORUS_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.PLATINUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.POTASSIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.RHENIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.RHODIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.RUBIDIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.RUTHENIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.SCANDIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.SELENIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.SILICON_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.SILVER_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.SODIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.STRONTIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.TANTALUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.TECHNETIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.TELLURIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.THALLIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.TIN_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.TITANIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.TUNGSTEN_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.VANADIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.YTTRIUM_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.ZINC_ORE.block().get());
        blockModels.createTrivialCube(ModBlocks.ZIRCONIUM_ORE.block().get());

        //Block - Block
        blockModels.createTrivialCube(ModBlocks.ALUMINIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.ANTIMONY_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.ARSENIC_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.BARIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.BERYLLIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.BISMUTH_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.CADMIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.CALCIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.CAESIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.CHROMIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.CINNABAR_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.COBALT_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.GERMANIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.GALLIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.HAFNIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.INDIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.IRIDIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.LEAD_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.LITHIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.MAGNESIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.MANGANESE_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.MOLYBDENUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.NICKEL_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.NIOBIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.OSMIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.PALLADIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.PHOSPHORUS_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.PLATINUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.POTASSIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RHENIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RHODIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RUBIDIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RUTHENIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.SCANDIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.SELENIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.SILICON_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.SILVER_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.SODIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.STRONTIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.TANTALUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.TECHNETIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.TELLURIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.THALLIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.TIN_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.TITANIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.TUNGSTEN_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.VANADIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.YTTRIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.ZINC_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.ZIRCONIUM_BLOCK.block().get());

        //Block - Raw Block
        blockModels.createTrivialCube(ModBlocks.RAW_ALUMINIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_ANTIMONY_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_ARSENIC_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_BARIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_BERYLLIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_BISMUTH_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_CADMIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_CALCIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_CAESIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_CHROMIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_CINNABAR_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_COBALT_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_GERMANIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_GALLIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_HAFNIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_INDIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_IRIDIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_LEAD_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_LITHIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_MAGNESIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_MANGANESE_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_MOLYBDENUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_NICKEL_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_NIOBIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_OSMIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_PALLADIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_PHOSPHORUS_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_PLATINUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_POTASSIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_RHENIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_RHODIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_RUBIDIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_RUTHENIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_SCANDIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_SELENIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_SILICON_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_SILVER_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_SODIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_STRONTIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_TANTALUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_TECHNETIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_TELLURIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_THALLIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_TIN_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_TITANIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_TUNGSTEN_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_VANADIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_YTTRIUM_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_ZINC_BLOCK.block().get());
        blockModels.createTrivialCube(ModBlocks.RAW_ZIRCONIUM_BLOCK.block().get());

        //Tools
        itemModels.generateFlatItem(ModItems.ALUMINIUM_SWORD.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(ModItems.ALUMINIUM_PICKAXE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(ModItems.ALUMINIUM_SHOVEL.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(ModItems.ALUMINIUM_AXE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(ModItems.ALUMINIUM_HOE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);

        itemModels.generateFlatItem(ModItems.SILVER_SWORD.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(ModItems.SILVER_PICKAXE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(ModItems.SILVER_SHOVEL.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(ModItems.SILVER_AXE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(ModItems.SILVER_HOE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);

        itemModels.generateFlatItem(ModItems.TECHNETIUM_SWORD.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(ModItems.TECHNETIUM_PICKAXE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(ModItems.TECHNETIUM_SHOVEL.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(ModItems.TECHNETIUM_AXE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(ModItems.TECHINETIUM_HOE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);

        itemModels.generateFlatItem(ModItems.TITANIUM_SWORD.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(ModItems.TITANIUM_PICKAXE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(ModItems.TITANIUM_SHOVEL.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(ModItems.TITANIUM_AXE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(ModItems.TITANIUM_HOE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);

        itemModels.generateFlatItem(ModItems.ALUMINIUM_HELMET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ALUMINIUM_CHESTPLATE.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ALUMINIUM_LEGGINGS.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ALUMINIUM_BOOTS.get(), ModelTemplates.FLAT_ITEM);

        itemModels.generateFlatItem(ModItems.SILVER_HELMET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SILVER_CHESTPLATE.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SILVER_LEGGINGS.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SILVER_BOOTS.get(), ModelTemplates.FLAT_ITEM);

        itemModels.generateFlatItem(ModItems.TECHNETIUM_HELMET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TECHNETIUM_CHESTPLATE.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TECHNETIUM_LEGGINGS.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TECHNETIUM_BOOTS.get(), ModelTemplates.FLAT_ITEM);

        itemModels.generateFlatItem(ModItems.TITANIUM_HELMET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TITANIUM_CHESTPLATE.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TITANIUM_LEGGINGS.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TITANIUM_BOOTS.get(), ModelTemplates.FLAT_ITEM);

        itemModels.generateFlatItem(ModItems.ALUMINIUM_AXEHEAD.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ALUMINIUM_BLADE.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ALUMINIUM_GUARD.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ALUMINIUM_HILT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ALUMINIUM_PICK.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ALUMINIUM_PLATE.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ALUMINIUM_POMMEL.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ALUMINIUM_SHOVELHEAD.get(), ModelTemplates.FLAT_ITEM);

        itemModels.generateFlatItem(ModItems.SILVER_AXEHEAD.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SILVER_BLADE.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SILVER_GUARD.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SILVER_HILT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SILVER_PICK.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SILVER_PLATE.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SILVER_POMMEL.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.SILVER_SHOVELHEAD.get(), ModelTemplates.FLAT_ITEM);

        itemModels.generateFlatItem(ModItems.TECHNETIUM_AXEHEAD.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TECHNETIUM_BLADE.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TECHNETIUM_GUARD.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TECHNETIUM_HILT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TECHNETIUM_PICK.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TECHNETIUM_PLATE.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TECHNETIUM_POMMEL.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TECHNETIUM_SHOVELHEAD.get(), ModelTemplates.FLAT_ITEM);

        itemModels.generateFlatItem(ModItems.TITANIUM_AXEHEAD.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TITANIUM_BLADE.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TITANIUM_GUARD.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TITANIUM_HILT.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TITANIUM_PICK.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TITANIUM_PLATE.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TITANIUM_POMMEL.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.TITANIUM_SHOVELHEAD.get(), ModelTemplates.FLAT_ITEM);

        itemModels.generateFlatItem(ModItems.FABRIC_STRAP.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.FABRIC_GRIP.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.LEATHER_STRAP.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.LEATHER_GRIP.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(ModItems.ARMOUR_PADDING.get(), ModelTemplates.FLAT_ITEM);
    }
}
