package com.megalogaminguk.megalosaio.datagen;

import com.megalogaminguk.megalosaio.Constants;
import com.megalogaminguk.megalosaio.init.ModBlocks;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.neoforged.neoforge.common.data.BlockTagsProvider;

import java.util.concurrent.CompletableFuture;

public class MegalosAIOBlockTagProvider extends BlockTagsProvider {
    public MegalosAIOBlockTagProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider) {
        super(output, lookupProvider, Constants.MOD_ID);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {
        tag(BlockTags.MINEABLE_WITH_PICKAXE)
                //Blocks - Ore
                .add(ModBlocks.ALUMINIUM_ORE.block().get())
                .add(ModBlocks.ANTIMONY_ORE.block().get())
                .add(ModBlocks.ARSENIC_ORE.block().get())
                .add(ModBlocks.BARIUM_ORE.block().get())
                .add(ModBlocks.BERYLLIUM_ORE.block().get())
                .add(ModBlocks.BISMUTH_ORE.block().get())
                .add(ModBlocks.CADMIUM_ORE.block().get())
                .add(ModBlocks.CALCIUM_ORE.block().get())
                .add(ModBlocks.CAESIUM_ORE.block().get())
                .add(ModBlocks.CHROMIUM_ORE.block().get())
                .add(ModBlocks.CINNABAR_ORE.block().get())
                .add(ModBlocks.COBALT_ORE.block().get())
                .add(ModBlocks.GERMANIUM_ORE.block().get())
                .add(ModBlocks.GALLIUM_ORE.block().get())
                .add(ModBlocks.HAFNIUM_ORE.block().get())
                .add(ModBlocks.INDIUM_ORE.block().get())
                .add(ModBlocks.IRIDIUM_ORE.block().get())
                .add(ModBlocks.LEAD_ORE.block().get())
                .add(ModBlocks.LITHIUM_ORE.block().get())
                .add(ModBlocks.MAGNESIUM_ORE.block().get())
                .add(ModBlocks.MANGANESE_ORE.block().get())
                .add(ModBlocks.MOLYBDENUM_ORE.block().get())
                .add(ModBlocks.NICKEL_ORE.block().get())
                .add(ModBlocks.NIOBIUM_ORE.block().get())
                .add(ModBlocks.OSMIUM_ORE.block().get())
                .add(ModBlocks.PALLADIUM_ORE.block().get())
                .add(ModBlocks.PHOSPHORUS_ORE.block().get())
                .add(ModBlocks.PLATINUM_ORE.block().get())
                .add(ModBlocks.POTASSIUM_ORE.block().get())
                .add(ModBlocks.RHENIUM_ORE.block().get())
                .add(ModBlocks.RHODIUM_ORE.block().get())
                .add(ModBlocks.RUBIDIUM_ORE.block().get())
                .add(ModBlocks.RUTHENIUM_ORE.block().get())
                .add(ModBlocks.SCANDIUM_ORE.block().get())
                .add(ModBlocks.SELENIUM_ORE.block().get())
                .add(ModBlocks.SILICON_ORE.block().get())
                .add(ModBlocks.SILVER_ORE.block().get())
                .add(ModBlocks.SODIUM_ORE.block().get())
                .add(ModBlocks.STRONTIUM_ORE.block().get())
                .add(ModBlocks.TANTALUM_ORE.block().get())
                .add(ModBlocks.TECHNETIUM_ORE.block().get())
                .add(ModBlocks.TELLURIUM_ORE.block().get())
                .add(ModBlocks.THALLIUM_ORE.block().get())
                .add(ModBlocks.TIN_ORE.block().get())
                .add(ModBlocks.TITANIUM_ORE.block().get())
                .add(ModBlocks.TUNGSTEN_ORE.block().get())
                .add(ModBlocks.VANADIUM_ORE.block().get())
                .add(ModBlocks.YTTRIUM_ORE.block().get())
                .add(ModBlocks.ZINC_ORE.block().get())
                .add(ModBlocks.ZIRCONIUM_ORE.block().get())

                //Blocks - Block
                .add(ModBlocks.ALUMINIUM_BLOCK.block().get())
                .add(ModBlocks.ANTIMONY_BLOCK.block().get())
                .add(ModBlocks.ARSENIC_BLOCK.block().get())
                .add(ModBlocks.BARIUM_BLOCK.block().get())
                .add(ModBlocks.BERYLLIUM_BLOCK.block().get())
                .add(ModBlocks.BISMUTH_BLOCK.block().get())
                .add(ModBlocks.CADMIUM_BLOCK.block().get())
                .add(ModBlocks.CALCIUM_BLOCK.block().get())
                .add(ModBlocks.CAESIUM_BLOCK.block().get())
                .add(ModBlocks.CHROMIUM_BLOCK.block().get())
                .add(ModBlocks.CINNABAR_BLOCK.block().get())
                .add(ModBlocks.COBALT_BLOCK.block().get())
                .add(ModBlocks.GERMANIUM_BLOCK.block().get())
                .add(ModBlocks.GALLIUM_BLOCK.block().get())
                .add(ModBlocks.HAFNIUM_BLOCK.block().get())
                .add(ModBlocks.INDIUM_BLOCK.block().get())
                .add(ModBlocks.IRIDIUM_BLOCK.block().get())
                .add(ModBlocks.LEAD_BLOCK.block().get())
                .add(ModBlocks.LITHIUM_BLOCK.block().get())
                .add(ModBlocks.MAGNESIUM_BLOCK.block().get())
                .add(ModBlocks.MANGANESE_BLOCK.block().get())
                .add(ModBlocks.MOLYBDENUM_BLOCK.block().get())
                .add(ModBlocks.NICKEL_BLOCK.block().get())
                .add(ModBlocks.NIOBIUM_BLOCK.block().get())
                .add(ModBlocks.OSMIUM_BLOCK.block().get())
                .add(ModBlocks.PALLADIUM_BLOCK.block().get())
                .add(ModBlocks.PHOSPHORUS_BLOCK.block().get())
                .add(ModBlocks.PLATINUM_BLOCK.block().get())
                .add(ModBlocks.POTASSIUM_BLOCK.block().get())
                .add(ModBlocks.RHENIUM_BLOCK.block().get())
                .add(ModBlocks.RHODIUM_BLOCK.block().get())
                .add(ModBlocks.RUBIDIUM_BLOCK.block().get())
                .add(ModBlocks.RUTHENIUM_BLOCK.block().get())
                .add(ModBlocks.SCANDIUM_BLOCK.block().get())
                .add(ModBlocks.SELENIUM_BLOCK.block().get())
                .add(ModBlocks.SILICON_BLOCK.block().get())
                .add(ModBlocks.SILVER_BLOCK.block().get())
                .add(ModBlocks.SODIUM_BLOCK.block().get())
                .add(ModBlocks.STRONTIUM_BLOCK.block().get())
                .add(ModBlocks.TANTALUM_BLOCK.block().get())
                .add(ModBlocks.TECHNETIUM_BLOCK.block().get())
                .add(ModBlocks.TELLURIUM_BLOCK.block().get())
                .add(ModBlocks.THALLIUM_BLOCK.block().get())
                .add(ModBlocks.TIN_BLOCK.block().get())
                .add(ModBlocks.TITANIUM_BLOCK.block().get())
                .add(ModBlocks.TUNGSTEN_BLOCK.block().get())
                .add(ModBlocks.VANADIUM_BLOCK.block().get())
                .add(ModBlocks.YTTRIUM_BLOCK.block().get())
                .add(ModBlocks.ZINC_BLOCK.block().get())
                .add(ModBlocks.ZIRCONIUM_BLOCK.block().get())

                //Blocks - Raw Block
                .add(ModBlocks.RAW_ALUMINIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_ANTIMONY_BLOCK.block().get())
                .add(ModBlocks.RAW_ARSENIC_BLOCK.block().get())
                .add(ModBlocks.RAW_BARIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_BERYLLIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_BISMUTH_BLOCK.block().get())
                .add(ModBlocks.RAW_CADMIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_CALCIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_CAESIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_CHROMIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_CINNABAR_BLOCK.block().get())
                .add(ModBlocks.RAW_COBALT_BLOCK.block().get())
                .add(ModBlocks.RAW_GERMANIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_GALLIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_HAFNIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_INDIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_IRIDIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_LEAD_BLOCK.block().get())
                .add(ModBlocks.RAW_LITHIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_MAGNESIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_MANGANESE_BLOCK.block().get())
                .add(ModBlocks.RAW_MOLYBDENUM_BLOCK.block().get())
                .add(ModBlocks.RAW_NICKEL_BLOCK.block().get())
                .add(ModBlocks.RAW_NIOBIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_OSMIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_PALLADIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_PHOSPHORUS_BLOCK.block().get())
                .add(ModBlocks.RAW_PLATINUM_BLOCK.block().get())
                .add(ModBlocks.RAW_POTASSIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_RHENIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_RHODIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_RUBIDIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_RUTHENIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_SCANDIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_SELENIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_SILICON_BLOCK.block().get())
                .add(ModBlocks.RAW_SILVER_BLOCK.block().get())
                .add(ModBlocks.RAW_SODIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_STRONTIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_TANTALUM_BLOCK.block().get())
                .add(ModBlocks.RAW_TECHNETIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_TELLURIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_THALLIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_TIN_BLOCK.block().get())
                .add(ModBlocks.RAW_TITANIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_TUNGSTEN_BLOCK.block().get())
                .add(ModBlocks.RAW_VANADIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_YTTRIUM_BLOCK.block().get())
                .add(ModBlocks.RAW_ZINC_BLOCK.block().get())
                .add(ModBlocks.RAW_ZIRCONIUM_BLOCK.block().get());

        tag(BlockTags.NEEDS_IRON_TOOL)
                //Blocks - Ore
                .add(ModBlocks.ALUMINIUM_ORE.block().get())

                //Blocks - Block
                .add(ModBlocks.ALUMINIUM_BLOCK.block().get())

                //Blocks - Raw Blocks
                .add(ModBlocks.RAW_ALUMINIUM_BLOCK.block().get());
    }
}
